// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (customer_id) VALUES ($1) RETURNING id, customer_id, created_at
`

func (q *Queries) CreateOrder(ctx context.Context, customerID pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, customerID)
	var i Order
	err := row.Scan(&i.ID, &i.CustomerID, &i.CreatedAt)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, quantity, price_in_cents)
VALUES ($1, $2, $3, $4) RETURNING id, order_id, product_id, quantity, price_in_cents, created_at
`

type CreateOrderItemParams struct {
	OrderID      int64 `json:"order_id"`
	ProductID    int64 `json:"product_id"`
	Quantity     int32 `json:"quantity"`
	PriceInCents int32 `json:"price_in_cents"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceInCents,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceInCents,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, hashed_password)
VALUES ($1, $2, $3, $4) RETURNING id, username, email, hashed_password, created_at
`

type CreateUserParams struct {
	ID             pgtype.UUID `json:"id"`
	Username       string      `json:"username"`
	Email          string      `json:"email"`
	HashedPassword string      `json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const decreaseProductStock = `-- name: DecreaseProductStock :exec
UPDATE products
SET quantity = quantity - $1
WHERE id = $2 AND quantity >= $1
`

type DecreaseProductStockParams struct {
	Quantity int32 `json:"quantity"`
	ID       int64 `json:"id"`
}

func (q *Queries) DecreaseProductStock(ctx context.Context, arg DecreaseProductStockParams) error {
	_, err := q.db.Exec(ctx, decreaseProductStock, arg.Quantity, arg.ID)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, price_in_cents, quantity, created_at FROM products WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmailIgnoreCase = `-- name: GetUserByEmailIgnoreCase :one
SELECT id, username, email, hashed_password, created_at FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmailIgnoreCase(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailIgnoreCase, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsernameIgnoreCase = `-- name: GetUserByUsernameIgnoreCase :one
SELECT id, username, email, hashed_password, created_at FROM users WHERE lower(username) = lower($1)
`

func (q *Queries) GetUserByUsernameIgnoreCase(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameIgnoreCase, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price_in_cents, quantity, created_at FROM products
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCents,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
